<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UnitsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = Carbon::now();
        $units = array(
            // PO
            array('station' => 301,
                 'numeral' => 'PO_151',
                 'name' => 'ARM_DURANGO',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 302,
                 'numeral' => 'PO_152',
                 'name' => 'ARM_SONORA',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 303,
                 'numeral' => 'PO_153',
                 'name' => 'ARM_GUANAJUATO',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 304,
                 'numeral' => 'PO_154',
                 'name' => 'ARM_VERACRUZ',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 305,
                 'numeral' => 'PO_161',
                 'name' => 'ARM_OAXACA',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 306,
                 'numeral' => 'PO_162',
                 'name' => 'ARM_CALIFORNIA',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 307,
                 'numeral' => 'PO_163',
                 'name' => 'ARM_INDEPENDENCIA',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 308,
                 'numeral' => 'PO_164',
                 'name' => 'ARM_REVOLUCION',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 314,
                 'numeral' => 'PO_165',
                 'name' => 'ARM_CHIAPAS',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 315,
                 'numeral' => 'PO_166',
                 'name' => 'ARM_HIDALGO',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            // PI
            array('station' => 501,
                 'numeral' => 'PI_1118',
                 'name' => 'ARM_HADAR',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 502,
                 'numeral' => 'PI_1119',
                 'name' => 'ARM_SHAULA',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 503,
                 'numeral' => 'PI_1121',
                 'name' => 'ARM_ANKAA',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 504,
                 'numeral' => 'PI_1122',
                 'name' => 'ARM_BELLATRIX',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 505,
                 'numeral' => 'PI_1130',
                 'name' => 'ARM_NUNKY',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 506,
                 'numeral' => 'PI_1138',
                 'name' => 'ARM_KOCHAB',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 507,
                 'numeral' => 'PI_1139',
                 'name' => 'ARM_ENIF',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 508,
                 'numeral' => 'PI_1147',
                 'name' => 'ARM_MENKAR',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 509,
                 'numeral' => 'PI_1148',
                 'name' => 'ARM_SABIK',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 510,
                 'numeral' => 'PI_1301',
                 'name' => 'ARM_ACUARIO',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 2,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            // KING AIR
            array('station' => 611,
                 'numeral' => 'ANX_1191',
                 'name' => 'ANX_1191_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 1,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            // KING AIR
            array('station' => 612,
                 'numeral' => 'ANX_1192',
                 'name' => 'ANX_1192_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 1,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 613,
                 'numeral' => 'ANX_1193',
                 'name' => 'ANX_1193_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 1,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 614,
                 'numeral' => 'ANX_1194',
                 'name' => 'ANX_1194_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 1,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 615,
                 'numeral' => 'ANX_1195',
                 'name' => 'ANX_1195_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 1,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 616,
                 'numeral' => 'ANX_1196',
                 'name' => 'ANX_1196_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 1,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 617,
                 'numeral' => 'ANX_1197',
                 'name' => 'ANX_1197_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 1,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             array('station' => 618,
                 'numeral' => 'ANX_1198',
                 'name' => 'ANX_1198_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 1,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             array('station' => 619,
                 'numeral' => 'ANX_1199',
                 'name' => 'ANX_1199_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 2,
                 'unit_type_id' => 1,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             // MANDO
             array('station' => 801,
                 'numeral' => 'SEDAM_EMG_1',
                 'name' => 'SEDAM_EMG_1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             array('station' => 811,
                 'numeral' => 'SEDAM_FUERNAVGO1',
                 'name' => 'SEDAM_FUERNAVGO1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             array('station' => 814,
                 'numeral' => 'SEDAM_FUERNAVPA1',
                 'name' => 'SEDAM_FUERNAVPA1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             array('station' => 877,
                 'numeral' => 'SEDAM_NAVCOAT_1',
                 'name' => 'SEDAM_NAVCOAT_1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             array('station' => 878,
                 'numeral' => 'SEDAM_NAVTOP_1',
                 'name' => 'SEDAM_NAVTOP_1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             array('station' => 879,
                 'numeral' => 'SEDAM_NAVCAB_1',
                 'name' => 'SEDAM_NAVCAB_1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             array('station' => 880,
                 'numeral' => 'SEDAM_NAVCORT_1',
                 'name' => 'SEDAM_NAVCORT_1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
             array('station' => 881,
                 'numeral' => 'SEDAM_NAVROS_1',
                 'name' => 'SEDAM_NAVROS_1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 882,
                 'numeral' => 'SEDAM_NAVFEL_1',
                 'name' => 'SEDAM_NAVFEL_1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 883,
                 'numeral' => 'SEDAM_NAVIXT_1',
                 'name' => 'SEDAM_NAVIXT_1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 4,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              //IM
              array('station' => 631,
                 'numeral' => 'SEDAM_VEHICUL_1',
                 'name' => 'SEDAM_VEHICUL_1',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 632,
                 'numeral' => 'SEDAM_VEHICUL_2',
                 'name' => 'SEDAM_VEHICUL_2',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 633,
                 'numeral' => 'SEDAM_VEHICUL_3',
                 'name' => 'SEDAM_VEHICUL_3',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 634,
                 'numeral' => 'SEDAM_VEHICUL_4',
                 'name' => 'SEDAM_VEHICUL_4',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 635,
                 'numeral' => 'SEDAM_VEHICUL_5',
                 'name' => 'SEDAM_VEHICUL_5',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 636,
                 'numeral' => 'SEDAM_VEHICUL_6',
                 'name' => 'SEDAM_VEHICUL_6',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 637,
                 'numeral' => 'SEDAM_VEHICUL_7',
                 'name' => 'SEDAM_VEHICUL_7',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 638,
                 'numeral' => 'SEDAM_VEHICUL_8',
                 'name' => 'SEDAM_VEHICUL_8',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 639,
                 'numeral' => 'SEDAM_VEHICUL_9',
                 'name' => 'SEDAM_VEHICUL_9',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
              array('station' => 640,
                 'numeral' => 'SEDAM_VEHICUL_10',
                 'name' => 'SEDAM_VEHICUL_10',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 5,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            /*array('station' => 613,
                 'numeral' => 'ANX_1193',
                 'name' => 'ANX_1193_KING_A',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 3,
                 'sensor_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 518,
                 'numeral' => 'PI_1415',
                 'name' => 'ARM_MENKALINAN',
                 'serial_number' => '001',
                 'country' => 'MX',
                 'number_engines' => 1,
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 515,
                 'numeral' => 'P_151_1',
                 'name' => 'PI_DURANGO',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 514,
                 'numeral' => 'PI_1413',
                 'name' => 'ARM_ALFIRK',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 513,
                 'numeral' => 'PI_1412',
                 'name' => 'ARM_MINTAKA',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 512,
                 'numeral' => 'PI_1411',
                 'name' => 'ARM_ALNITAK',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 511,
                 'numeral' => 'PI_1410',
                 'name' => 'ARM_ALBIREO',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 510,
                 'numeral' => 'PI_1301',
                 'name' => 'ARM_ACUARIO',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 509,
                 'numeral' => 'PI_1148',
                 'name' => 'ARM_SABIK',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 508,
                 'numeral' => 'PI_1147',
                 'name' => 'ARM_MENKAR',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 507,
                 'numeral' => 'PI_1139',
                 'name' => 'ARM_ENIF',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 506,
                 'numeral' => 'PI_1138',
                 'name' => 'ARM_KOCHAB',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 504,
                 'numeral' => 'PI_1122',
                 'name' => 'ARM_BELLATRIX',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 502,
                 'numeral' => 'PI_1119',
                 'name' => 'ARM_SHAULA',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 501,
                 'numeral' => 'PI_1118',
                 'name' => 'ARM_HADAR',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 402,
                 'numeral' => 'PA_502',
                 'name' => 'ARM_TEOTIHUACAN',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 401,
                 'numeral' => 'PA_501',
                 'name' => 'ARM_TENOCHTITLAN',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 303,
                 'numeral' => 'PO_153',
                 'name' => 'ARM_GUANAJUATO',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 2,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 302,
                 'numeral' => 'PO_152',
                 'name' => 'ARM_SONORA',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 2,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 301,
                 'numeral' => 'PO_151',
                 'name' => 'ARM_DURANGO',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 2,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 503,
                 'numeral' => 'PI_1121',
                 'name' => 'ARM_ANKAA',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 505,
                 'numeral' => 'PI_1130',
                 'name' => 'ARM_NUNKI',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 ),
            array('station' => 516,
                 'numeral' => 'P_152_1',
                 'name' => 'PI_SONORA',
                 'serial_number' => '001',
                 'number_engines' => 1,
                 'country' => 'MX',
                 'unit_type_id' => 1,
                 'image' => 'image/image.jpg',
                 'created_at' => $date,
                 'updated_at' => $date
                 )*/
        );
        
        foreach ($units as $unit) {
        	$unit = \DB::table('units')->insert($unit); 
        }
    }
}
